inherit_from: ../.rubocop.yml

MethodLength:
  CountComments: false
  Max: 55

LineLength:
  Max: 170

Blocks:
  Enabled: false # {} for multi-line blocks in RSpec expectations is very common

TrivialAccessors:
  Enabled: false # Bosh::Dev::Infrastructure#light? was a false positive