inherit_from: ../.rubocop.yml

MethodLength:
  CountComments: false
  Max: 55

LineLength:
  Max: 240

TrivialAccessors:
  Enabled: false # Bosh::Dev::Infrastructure#light? was a false positive

AvoidPerlisms:
  Enabled: false
